[package]
name = "rustback"
version = "0.1.0"
edition = "2021"
authors= ["Vorosdev <vorosdev@gmail.com>"]
license = "MIT"
categories = ["remote-control", "backdoor"]

[dependencies]
capctl = "0.2.4"
tokio = { version = "1.40.0", features = ["full"] }
